[package]
name = "ks-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ks-core = { workspace = true, features = ["alloc"] }
egui_overlay.workspace = true
egui.workspace = true
glow = "0.13"
mlua.workspace = true
notify.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Dwm",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
] }
