[package]
name = "ks-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ks-core = { workspace = true, features = ["alloc"] }
egui_overlay.workspace = true
egui.workspace = true
glow = "0.13"
mlua.workspace = true
notify.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "sync", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true
